export {
  createVNextTextBlockMultiRunSemanticLineFactsV1 as createFlowDocTextEngineSemanticLineFactsV1,
  createVNextTextBlockMultiRunSemanticLineFingerprintV1 as createFlowDocTextEngineSemanticLineFingerprintV1,
} from "@flowdoc/vnext-core"
