import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

describe("vNext text engine adapter lane close audit", () => {
  it("documents the text engine adapter lane foundation pass without claiming concrete engine execution", () => {
    const readText = (path: string) => readFileSync(new URL(path, import.meta.url), "utf8")
    const auditDoc = readText("../docs/TEXT_ENGINE_ADAPTER_LANE_CLOSE_AUDIT.md")
    const readme = readText("../README.md")
    const ledger = readText("../docs/PHASE_LEDGER.md")
    const roadmap = readText("../docs/PHASE_18_IMPLEMENTATION_ROADMAP.md")

    expect(auditDoc).toContain("Status: Phase 111 close audit.")
    expect(auditDoc).toContain("This audit does not implement new runtime behavior.")
    expect(auditDoc).toContain("## PASS")
    expect(auditDoc).toContain("## FAIL / BLOCKER")
    expect(auditDoc).toContain("## RISK")
    expect(auditDoc).toContain("## UNKNOWN")
    expect(auditDoc).toContain("## Files Changed In This Pass")
    expect(auditDoc).toContain("## Behavior Changed")
    expect(auditDoc).toContain("## Tests Run")
    expect(auditDoc).toContain("## Risks Left")
    expect(auditDoc).toContain("## Intentionally Not Changed")
    expect(auditDoc).toContain("src/renderer/measurementProfileIdentity.ts")
    expect(auditDoc).toContain("src/renderer/rustWasmTextEngineBoundary.ts")
    expect(auditDoc).toContain("src/renderer/thaiCorpusBoundary.ts")
    expect(auditDoc).toContain("src/renderer/rustybuzzShapingSmoke.ts")
    expect(auditDoc).toContain("src/renderer/textEngineAdapterSpi.ts")
    expect(auditDoc).toContain("src/renderer/textEngineEvidenceAcceptance.ts")
    expect(auditDoc).toContain("src/renderer/textEngineMeasurementDraftHandoff.ts")
    expect(auditDoc).toContain("Glyph facts remain separate evidence")
    expect(auditDoc).toContain("No concrete adapter package.")
    expect(auditDoc).toContain("No rustybuzz, HarfBuzz, ICU4X, WASM")
    expect(auditDoc).toContain("No production measurement binding.")
    expect(readme).toContain("Text engine adapter lane close audit")
    expect(readme).toContain("docs/TEXT_ENGINE_ADAPTER_LANE_CLOSE_AUDIT.md")
    expect(ledger).toContain("| 111 | Text engine adapter lane close audit | done |")
    expect(roadmap).toContain("## Phase 111: Text Engine Adapter Lane Close Audit")
  })
})
